restart

--GB computations are done over a finite field, due to a lower runtime
FF = ZZ/32003
R = FF[vx,vz, ax,ay,az, a2x,a2y,a2z, a1,b1,c1]
d1 = 1
vy = 0

--the measurements are initialized at random; we end up in a generic case with a high probability
x1a = random FF
y1a = random FF
x1b = random FF
y1b = random FF
x1c = random FF
y1c = random FF
x1d = random FF
y1d = random FF
x1e = random FF
y1e = random FF
x1f = random FF
y1f = random FF
x1g = random FF
y1g = random FF
x1h = random FF
y1h = random FF
x1i = random FF
y1i = random FF
x1j = random FF
y1j = random FF
x1k = random FF
y1k = random FF


rotRS = a -> matrix{
        {1+a_(0,0)*a_(0,0)-a_(1,0)*a_(1,0)-a_(2,0)*a_(2,0), 2*a_(0,0)*a_(1,0)-2*a_(2,0), 2*a_(1,0)+2*a_(0,0)*a_(2,0)},
        {2*a_(2,0)+2*a_(0,0)*a_(1,0), 1-a_(0,0)*a_(0,0)+a_(1,0)*a_(1,0)-a_(2,0)*a_(2,0), 2*a_(1,0)*a_(2,0)-2*a_(0,0)},
        {2*a_(0,0)*a_(2,0)-2*a_(1,0), 2*a_(0,0)+2*a_(1,0)*a_(2,0), 1-a_(0,0)*a_(0,0)-a_(1,0)*a_(1,0)+a_(2,0)*a_(2,0)}
    }


--construct the matrices
Ld1 = matrix{{a1},{1},{b1}}
Ld1x = matrix{{0,-b1,1},{b1,0,-a1},{-1,a1,0}}
--
L1 = matrix{{c1},{0},{d1}}
V = matrix{{vx},{vy},{vz}}
A = matrix{{ax},{ay},{az}}
A2 = matrix{{a2x},{a2y},{a2z}}

u1a = matrix{{x1a,y1a,1}}
u1b = matrix{{x1b,y1b,1}}
u1c = matrix{{x1c,y1c,1}}
u1d = matrix{{x1d,y1d,1}}
u1e = matrix{{x1e,y1e,1}}
u1f = matrix{{x1f,y1f,1}}
u1g = matrix{{x1g,y1g,1}}
u1h = matrix{{x1h,y1h,1}}
u1i = matrix{{x1i,y1i,1}}
u1j = matrix{{x1j,y1j,1}}
u1k = matrix{{x1k,y1k,1}}

R1a = rotRS(y1a*A + y1a*y1a*A2)
R1b = rotRS(y1b*A + y1b*y1b*A2)
R1c = rotRS(y1c*A + y1c*y1c*A2)
R1d = rotRS(y1d*A + y1d*y1d*A2)
R1e = rotRS(y1e*A + y1e*y1e*A2)
R1f = rotRS(y1f*A + y1f*y1f*A2)
R1g = rotRS(y1g*A + y1g*y1g*A2)
R1h = rotRS(y1h*A + y1h*y1h*A2)
R1i = rotRS(y1i*A + y1i*y1i*A2)
R1j = rotRS(y1j*A + y1j*y1j*A2)
R1k = rotRS(y1k*A + y1k*y1k*A2)

--construct the equations
eqn1a = u1a * R1a * Ld1x * (L1 - y1a*V)
eqn1b = u1b * R1b * Ld1x * (L1 - y1b*V)
eqn1c = u1c * R1c * Ld1x * (L1 - y1c*V)
eqn1d = u1d * R1d * Ld1x * (L1 - y1d*V)
eqn1e = u1e * R1e * Ld1x * (L1 - y1e*V)
eqn1f = u1f * R1f * Ld1x * (L1 - y1f*V)
eqn1g = u1g * R1g * Ld1x * (L1 - y1g*V)
eqn1h = u1h * R1h * Ld1x * (L1 - y1h*V)
eqn1i = u1i * R1i * Ld1x * (L1 - y1i*V)
eqn1j = u1j * R1j * Ld1x * (L1 - y1j*V)
eqn1k = u1k * R1k * Ld1x * (L1 - y1k*V)



eqns = {eqn1a, eqn1b, eqn1c, eqn1d, eqn1e, eqn1f, eqn1g, eqn1h, eqn1i, eqn1j, eqn1k}

--define the ideal generated by the equations, and find its GB
Ispec = ideal eqns
elapsedTime G := groebnerBasis(Ispec, Strategy => "F4");

--use the GB to find the degree and dimension of the ideal
ltG := ideal leadTerm G; (dim ltG, degree ltG);
dimdeg := (dim ltG, degree ltG);
<< "(dim, degree) " << dimdeg << endl;

