restart
FF = ZZ/32003
R = FF[ax,ay,az, vx,vz, wx,wz, v3x,v3z, a,b,c]

x1a = random FF
y1a = random FF
x1b = random FF
y1b = random FF
x1c = random FF
y1c = random FF
x1d = random FF
y1d = random FF
x1e = random FF
y1e = random FF
x1f = random FF
y1f = random FF
x1g = random FF
y1g = random FF
x1h = random FF
y1h = random FF
x1i = random FF
y1i = random FF
x1j = random FF
y1j = random FF
x1k = random FF
y1k = random FF
x1l = random FF
y1l = random FF
d = 1


rotRS = a -> matrix{
        {1+a_(0,0)*a_(0,0)-a_(1,0)*a_(1,0)-a_(2,0)*a_(2,0), 2*a_(0,0)*a_(1,0)-2*a_(2,0), 2*a_(1,0)+2*a_(0,0)*a_(2,0)},
        {2*a_(2,0)+2*a_(0,0)*a_(1,0), 1-a_(0,0)*a_(0,0)+a_(1,0)*a_(1,0)-a_(2,0)*a_(2,0), 2*a_(1,0)*a_(2,0)-2*a_(0,0)},
        {2*a_(0,0)*a_(2,0)-2*a_(1,0), 2*a_(0,0)+2*a_(1,0)*a_(2,0), 1-a_(0,0)*a_(0,0)-a_(1,0)*a_(1,0)+a_(2,0)*a_(2,0)}
    }


A = matrix{{ax},{ay},{az}}
V = matrix{{vx},{0},{vz}}
W = matrix{{wx},{0},{wz}}
V3 = matrix{{v3x},{0},{v3z}}

Ld = matrix{{a},{1},{b}}
Ldx = matrix{{0,-b,1},{b,0,-a},{-1,a,0}}
L1 = matrix{{c},{0},{d}}

---

u1a = matrix{{x1a,y1a,1}}
u1b = matrix{{x1b,y1b,1}}
u1c = matrix{{x1c,y1c,1}}
u1d = matrix{{x1d,y1d,1}}
u1e = matrix{{x1e,y1e,1}}
u1f = matrix{{x1f,y1f,1}}
u1g = matrix{{x1g,y1g,1}}
u1h = matrix{{x1h,y1h,1}}
u1i = matrix{{x1i,y1i,1}}
u1j = matrix{{x1j,y1j,1}}
u1k = matrix{{x1k,y1k,1}}
u1l = matrix{{x1l,y1l,1}}

---

R1a = rotRS(y1a*A)
R1b = rotRS(y1b*A)
R1c = rotRS(y1c*A)
R1d = rotRS(y1d*A)
R1e = rotRS(y1e*A)
R1f = rotRS(y1f*A)
R1g = rotRS(y1g*A)
R1h = rotRS(y1h*A)
R1i = rotRS(y1i*A)
R1j = rotRS(y1j*A)
R1k = rotRS(y1k*A)
R1l = rotRS(y1l*A)

---

eqn1a = u1a * R1a * Ldx * (L1 - y1a*V - y1a^2*W - y1a^3*V3)
eqn1b = u1b * R1b * Ldx * (L1 - y1b*V - y1b^2*W - y1b^3*V3)
eqn1c = u1c * R1c * Ldx * (L1 - y1c*V - y1c^2*W - y1c^3*V3)
eqn1d = u1d * R1d * Ldx * (L1 - y1d*V - y1d^2*W - y1d^3*V3)
eqn1e = u1e * R1e * Ldx * (L1 - y1e*V - y1e^2*W - y1e^3*V3)
eqn1f = u1f * R1f * Ldx * (L1 - y1f*V - y1f^2*W - y1f^3*V3)
eqn1g = u1g * R1g * Ldx * (L1 - y1g*V - y1g^2*W - y1g^3*V3)
eqn1h = u1h * R1h * Ldx * (L1 - y1h*V - y1h^2*W - y1h^3*V3)
eqn1i = u1i * R1i * Ldx * (L1 - y1i*V - y1i^2*W - y1i^3*V3)
eqn1j = u1j * R1j * Ldx * (L1 - y1j*V - y1j^2*W - y1j^3*V3)
eqn1k = u1k * R1k * Ldx * (L1 - y1k*V - y1k^2*W - y1k^3*V3)
eqn1l = u1l * R1l * Ldx * (L1 - y1l*V - y1l^2*W - y1l^3*V3)



eqns = {eqn1a, eqn1b, eqn1c, eqn1d, eqn1e, eqn1f, eqn1g, eqn1h, eqn1i, eqn1j, eqn1k, eqn1l}

--define the ideal generated by the equations, and find its GB
Ispec = ideal eqns
elapsedTime G := groebnerBasis(Ispec, Strategy => "F4");

--use the GB to find the degree and dimension of the ideal
ltG := ideal leadTerm G; (dim ltG, degree ltG);
dimdeg := (dim ltG, degree ltG);
<< "(dim, degree) " << dimdeg << endl;


