restart

--GB computations are done over a finite field, due to a lower runtime
FF = ZZ/32003
R = FF[a,b, vx,vz, c1,d1,c2,d2,c3]

--the measurements are initialized at random; we end up in a generic case with a high probability
x1a = random FF
y1a = random FF
x1b = random FF
y1b = random FF
x1c = random FF
y1c = random FF

x2a = random FF
y2a = random FF
x2b = random FF
y2b = random FF
x2c = random FF
y2c = random FF

x3a = random FF
y3a = random FF
x3b = random FF
y3b = random FF
x3c = random FF
y3c = random FF

--construct the matrices
Ld = matrix{{a},{1},{b}}
Ldx = matrix{{0,-b,1},{b,0,-a},{-1,a,0}}
L1 = matrix{{c1},{0},{d1}}
L2 = matrix{{c2},{0},{d2}}
L3 = matrix{{c3},{0},{1}}
V = matrix{{vx},{0},{vz}}

u1a = matrix{{x1a,y1a,1}}
u1b = matrix{{x1b,y1b,1}}
u1c = matrix{{x1c,y1c,1}}

u2a = matrix{{x2a,y2a,1}}
u2b = matrix{{x2b,y2b,1}}
u2c = matrix{{x2c,y2c,1}}

u3a = matrix{{x3a,y3a,1}}
u3b = matrix{{x3b,y3b,1}}
u3c = matrix{{x3c,y3c,1}}


--construct the equations
eqn1a = u1a * Ldx * (L1 - y1a*V)
eqn1b = u1b * Ldx * (L1 - y1b*V)
eqn1c = u1c * Ldx * (L1 - y1c*V)

eqn2a = u2a * Ldx * (L2 - y2a*V)
eqn2b = u2b * Ldx * (L2 - y2b*V)
eqn2c = u2c * Ldx * (L2 - y2c*V)

eqn3a = u3a * Ldx * (L3 - y3a*V)
eqn3b = u3b * Ldx * (L3 - y3b*V)
eqn3c = u3c * Ldx * (L3 - y3c*V)

--print eqn1a



eqns = {eqn1a, eqn1b, eqn1c, eqn2a, eqn2b, eqn2c, eqn3a, eqn3b, eqn3c}

--define the ideal generated by the equations, and find its GB
Ispec = ideal eqns
elapsedTime G := groebnerBasis(Ispec, Strategy => "F4");

--use the GB to find the degree and dimension of the ideal
ltG := ideal leadTerm G; (dim ltG, degree ltG);
dimdeg := (dim ltG, degree ltG);
<< "(dim, degree) " << dimdeg << endl;

