restart

--GB computations are done over a finite field, due to a lower runtime
FF = ZZ/32003
R = FF[ax,ay,az, aax,aay,aaz, X1x,X1y,X2x,X2y,X3x,X3y]
X1z = 1
X2z = 1
X3z = 1

x1a = random FF
y1a = random FF
x1b = random FF
y1b = random FF
x2a = random FF
y2a = random FF
x2b = random FF
y2b = random FF
x3a = random FF
y3a = random FF
x3b = random FF
y3b = random FF

rotRS = a -> matrix{
        {1+a_(0,0)*a_(0,0)-a_(1,0)*a_(1,0)-a_(2,0)*a_(2,0), 2*a_(0,0)*a_(1,0)-2*a_(2,0), 2*a_(1,0)+2*a_(0,0)*a_(2,0)},
        {2*a_(2,0)+2*a_(0,0)*a_(1,0), 1-a_(0,0)*a_(0,0)+a_(1,0)*a_(1,0)-a_(2,0)*a_(2,0), 2*a_(1,0)*a_(2,0)-2*a_(0,0)},
        {2*a_(0,0)*a_(2,0)-2*a_(1,0), 2*a_(0,0)+2*a_(1,0)*a_(2,0), 1-a_(0,0)*a_(0,0)-a_(1,0)*a_(1,0)+a_(2,0)*a_(2,0)}
    }

skewMatrix = (u) -> (
    if (numrows u != 3 or numcols u != 1) then
        error "Input must be a 3x1 matrix";
    u1 := u_(0,0);
    u2 := u_(1,0);
    u3 := u_(2,0);
    matrix{
        { 0,   -u3,    u2 },
        {  u3,   0,   -u1 },
        { -u2,    u1,   0 }
    }
);


A = matrix{{ax},{ay},{az}}
AA = matrix{{aax},{aay},{aaz}}
X1 = matrix{{X1x},{X1y},{X1z}}
X2 = matrix{{X2x},{X2y},{X2z}}
X3 = matrix{{X3x},{X3y},{X3z}}

---

u1a = matrix{{x1a},{y1a},{1}}
u1b = matrix{{x1b},{y1b},{1}}

u2a = matrix{{x2a},{y2a},{1}}
u2b = matrix{{x2b},{y2b},{1}}

u3a = matrix{{x3a},{y3a},{1}}
u3b = matrix{{x3b},{y3b},{1}}

u1ax = skewMatrix(u1a)
u1bx = skewMatrix(u1b)

u2ax = skewMatrix(u2a)
u2bx = skewMatrix(u2b)

u3ax = skewMatrix(u3a)
u3bx = skewMatrix(u3b)

---

R1a = rotRS(y1a*A + y1a*y1a*AA)
R1b = rotRS(y1b*A + y1b*y1b*AA)

R2a = rotRS(y2a*A + y2a*y2a*AA)
R2b = rotRS(y2b*A + y2b*y2b*AA)

R3a = rotRS(y3a*A + y3a*y3a*AA)
R3b = rotRS(y3b*A + y3b*y3b*AA)

---

eqn1a = u1ax * R1a * X1
eqn1b = u1bx * R1b * X1

eqn2a = u2ax * R2a * X2
eqn2b = u2bx * R2b * X2

eqn3a = u3ax * R3a * X3
eqn3b = u3bx * R3b * X3



eqns = eqn1a || eqn1b || eqn2a || eqn2b || eqn3a || eqn3b

--define the ideal generated by the equations, and find its GB
Ispec = ideal eqns
elapsedTime G := groebnerBasis(Ispec, Strategy => "F4");

--use the GB to find the degree and dimension of the ideal
ltG := ideal leadTerm G; (dim ltG, degree ltG);
dimdeg := (dim ltG, degree ltG);
<< "(dim, degree) " << dimdeg << endl;


